name: CI
on:
  push:

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo
      - name: setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt, clippy
      - name: compile source
        uses: actions-rs/cargo@v1
        with:
          command: build
      - name: upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: target
          retention-days: 1
  clippy:
    runs-on: Ubuntu-20.04
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
      - name: setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            components: rustfmt, clippy
      - name: run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
