on:
  push:
    tags:
      - v*.*.*

jobs:
  release-image:
    name: release image
    runs-on: Ubuntu-20.04
    environment:
      APP: sweeprs
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Parse semver string
        id: semver_parser 
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'
      - name: Build and push tags
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: ilmannafian/${{ env.APP }}:latest
          tags: |
            ilmannafian/${{ env.APP }}:latest
            ilmannafian/${{ env.APP }}:${{ steps.semver_parser.outputs.major }}
            ilmannafian/${{ env.APP }}:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}
            ilmannafian/${{ env.APP }}:${{ steps.semver_parser.outputs.major }}.${{ steps.semver_parser.outputs.minor }}.${{ steps.semver_parser.outputs.patch }}
